### PR TITLE
ACF Post Object filter: guard against empty post id

### PR DESCRIPTION
**Pull request by jacobarriola**
What does this implement/fix? Explain your changes.
---------------------------------------------------
Adds a guard against the post id when attempting to set the correct Type source for an ACF Post Object field. This guard will return the correct value (`null`) instead of an unexpected query result (incorrect/duplicate product/order/coupon). 

There could be instances where the post id is empty because an end-user saved an empty value in the WP admin UI. It is better to get a `null` value instead of the incorrect product/order/coupon result.

For more details, see #406

Does this close any currently open issues?
------------------------------------------
#406

### CODE REVIEW

**Comment by jacobarriola** [comment]
Hey @kidunot89 👋🏽 

I'm going to be stepping away during the holidays soon, so let me know whether this PR seems acceptable to you or whether I need to make some changes. Thanks!

**Review by kidunot89 — APPROVED** [review]
@jacobarriola Sorry, for the delay on this review. Great work on this :+1:

**Review by kidunot89 — CHANGES_REQUESTED** [review]
@jacobarriola Upon further review, this function may not be necessary anymore. 

I suggest changing Line 26 to `add_filter( 'graphql_acf_post_object_source', array( '\WPGraphQL\WooCommerce\Data\Loader\WC_CPT_Loader', 'resolve_model' ), 10, 2 );`

**Comment by jacobarriola** [comment]
@kidunot89 Sounds good. I'll take look and test it out.

**Comment by kidunot89** [comment]
@jacobarriola There is however an core design issue that is preventing Products and other WPGraphQL Costs from being registered to WPGraphQL core `PostObjectUnion` type which is typically the type resolved for the ACF `post_object` relationship fields. After much discussion with @jasonbahl we still haven't fully resolved this. There's a lot of moving pieces in play on this.

**Comment by jacobarriola** [comment]
@kidunot89 With regards to the design issue, is this the issue you're referring to? https://github.com/wp-graphql/wp-graphql-acf/pull/177

**Comment by kidunot89** [comment]
@jacobarriola This shouldn't be necessary after the next release. Even less so have the next major release of WPGraphQL ACF.

**Pull request closed without merging**
