### PR TITLE
Feature/stripe payment gateway support

### PR DESCRIPTION
**Pull request by kidunot89**
### Your checklist for this pull request
Thanks for sending a pull request! Please make sure you click the link above to view the contribution guidelines, then fill out the blanks below.

🚨Please review the [guidelines for contributing](./CONTRIBUTING.md) to this repository.

- [x] Make sure you are making a pull request against the **develop branch** (left side). Also you should start *your branch* off *our develop*.
- [x] Make sure you are requesting to pull request from a **topic/feature/bugfix branch** (right side). Don't pull request from your master!

What does this implement/fix? Explain your changes.
---------------------------------------------------
Adds supports for processing payments using the Stripe payment gateway and the `checkout` mutation.
- To do this the IDs of the *Stripe Customer*, *Source*, and *Payment Intent* objects connected to the future order must be provided as `_stripe_customer_id`, `_stripe_source_id`, and `_stripe_intent_id` to the `metaData` field in the `CheckoutInput` when executing the mutation.
- This only works with the Stripe payment gateway currently as far as I know, however other payment gateways may use WooCommerce order meta field to process order payments.
- If you need a explain of sorts you can view [this](https://github.com/kidunot89/wp-graphql-woocommerce/blob/feature/stripe-payment-gateway-support/tests/wpunit/CheckoutMutationTest.php#L1103-L1489) test. The `stripe/stripe-php` library is used to execute the Stripe API requests and create the stripe objects. This process can also be in client-side in Javascript with the Stripe JavaScript libraries and it's encouraged.

Does this close any currently open issues?
------------------------------------------
…

Any relevant logs, error output, GraphiQL screenshots, etc?
-------------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
…

Where has this been tested?
---------------------------
**Operating System:** Linux Mint 19.2

**WordPress Version:** 5.2.3

### CODE REVIEW

**Comment by renatonascalves** [comment]
Is this a first attempt/try at #25?

**Comment by kidunot89** [comment]
Yes and no, the issue is kinda of broad and covers a larger part of the schema then this. This is a small patch that uses an extra parameter on the `WC_Gateway_Stripe::process_payment()` to force Stripe object ID retrieval from the order meta instead of the `$_POST` global. It's not a breaking change and Stripe has so much popularity that I didn't see an issue with adding it.

**Comment by renatonascalves** [comment]
Understood! I don't see an issue either. Just trying to understand the bigger picture with this PR. Tks for the feedback. :)

**Comment by rodrigoreeis** [comment]
I'm still a little lost in relation to this release how do I use it on the front in me mutation ?

**Comment by kidunot89** [comment]
@rodrigoreeis First you would Stripe **Customer**, **Source**, and **Payment Intent** objects using Stripe.js or one of the other Stripe libraries, then you would pass the IDs of each of those objects as meta on the order.

I plan on writing a guide or tutorial on this later, but for now I recommend just viewing this [test](https://github.com/wp-graphql/wp-graphql-woocommerce/blob/release/v0.5.1/tests/wpunit/CheckoutMutationTest.php#L1069-L1133) as well as the Stripe helper functions using the `stripe/stripe-php` package. All of the functionality from that package is available in the other Stripe libraries on other platforms.

If it helps the part the may be the most complex is the creation of the source. The stripe **source** is the instrument of payment, _e.g. credit card, bank info_. The test uses a [test source](https://github.com/wp-graphql/wp-graphql-woocommerce/blob/release/v0.5.1/tests/wpunit/CheckoutMutationTest.php#L1094-L1097) provide by the stripe api for the purpose of testing only.

**Comment by rodrigoreeis** [comment]
@kidunot89 anyway I will have to use some example stripe library [stripe/react-stripe-elements](https://github.com/stripe/react-stripe-elements)  ?? and I'm still not quite understanding what the role of these fields is `_stripe_customer_id`, `_stripe_source_id` and `_stripe_intent_id`. I need to confess im lost... :sweat_smile:

**Comment by rodrigoreeis** [comment]
@kidunot89 I believe that it will not be necessary to answer my question above, I am understanding the fields and the code.

I would like to thank you for the great job you are doing with this plugin !! I will probably open some PR in the documentation to be able to make the plugin documentation !

Thanks God bless youuu

**Comment by jlundgren77** [comment]
Trying to use checkout mutation with Stripe and coming up empty.  

Within the mutation I am passing in as metaData: [ {key: "_stripe_source_id", value: "xxx"}, {key: "_stripe_intent_id", value: "xxx"}, {key: "_stripe_customer_id, value:"xxx}].  These values are being generated server side.  
The order shows up in the Wordpress dashboard, but it's not being processed.  It shows up as processing.

Any thoughts on what could be going on?

**Comment by jonlovera** [comment]
### Just a quick note
For anyone who arrives at this pull request wondering if all `metaData` is required. No all of them are required at the same time. If you are working with [Stripe.js](https://stripe.com/docs/js) or [@stripe/react-stripe-js](https://github.com/stripe/react-stripe-js) you could use the `_stripe_source_id` to process the order. You can create the `_stripe_source_id` using `stripe.createSource` for example.

**Comment by darrylmorley** [comment]
@kidunot89 Your link for the example of how this is implemented does not work, do you have an updated link please?

**Comment by MobyDigg** [comment]
@kidunot89 the links in your examples do not work anymore. Can you update them?

**Comment by jacobarriola** [comment]
@MobyDigg @darrylmorley I think the test is here now: https://github.com/wp-graphql/wp-graphql-woocommerce/blob/develop/tests/wpunit/CheckoutMutationTest.php#L1153

**Comment by jacobarriola** [comment]
@MobyDigg @darrylmorley I messed around with checkout + Stripe over the holidays (with Gatsby) and wrote a blog post about it -> https://jacobarriola.com/post/headless-woocommerce-stripe-checkout-graphql

I hope it helps!

cc @kidunot89

**Pull request merged**
