### PR TITLE
QL Session Handler

### PR DESCRIPTION
**Pull request by kidunot89**
### Your checklist for this pull request
Thanks for sending a pull request! Please make sure you click the link above to view the contribution guidelines, then fill out the blanks below.

🚨Please review the [guidelines for contributing](./CONTRIBUTING.md) to this repository.

- [x] Make sure you are making a pull request against the **develop branch** (left side). Also you should start *your branch* off *our develop*.
- [x] Make sure you are requesting to pull request from a **topic/feature/bugfix branch** (right side). Don't pull request from your master!

What does this implement/fix? Explain your changes.
---------------------------------------------------
Implements *QL_Session_Handler* and filters it in using the [`woocommerce_session_handler`](https://docs.woocommerce.com/wc-apidocs/source-class-WooCommerce.html#531) hook on GraphQL requests. It functions essentially the same as the core session handler with one key difference, instead of saving the session data to a cookie, it encrypts the data and saves it to a header. `woocoommerce-session` is the default header name but this can be alternated with a filter `woocommerce_session_header_name`. 

In order to use the session header the valid unaltered session data must be passed as a header with the same name as the session header the data was retrieve from. Upon creation or changes to the session key, the session header is pass with the new value. When the session is destroyed, like when the user logs out, the session header is pass with the value 'false'.

It's recommend that when use the session header middleware and afterware functionality be leverage on the respective GraphQL client. See below for example of how to do with [ApolloClient](https://www.apollographql.com/docs/react/advanced/network-layer/) and the [`apollo-link`](https://github.com/apollographql/apollo-link) library.

#### Example client-side implemention  with ApolloClient
```
import { ApolloClient } from 'apollo-client';
import { HttpLink } from 'apollo-link-http';
import { ApolloLink } from 'apollo-link';

const httpLink = new HttpLink({
  uri: 'http://example.com/wordpress/graphql',
});

// middleware operation
export const middleware = new ApolloLink((operation, forward) => {
  /**
   * If session data exist in local storage, set value as session header.
   */
  const session = localStorage.getItem('woo-session');
  if (session) {
    operation.setContext(({ headers = {} }) => ({
      headers: {
        ...headers,
        'woocommerce-session': session,
      }
    }));
  }

  return forward(operation);
});

// afterware operation
export const afterware = new ApolloLink((operation, forward) => {
  return forward(operation).map((response) => {
    /**
     * Check for session header and update session in local storage accordingly. 
     */
    const context = operation.getContext();
    const { response: { headers } } = context;
    const session = headers.get('woocommerce-session');
    if (session) {
      // remove session data if session destroyed.
      if ( 'false' === session ) {
        localStorage.removeItem('woo-session');
      // update session new data if changed. 
      } else if ( localStorage.getItem('woo-session') !== session ) {
        localStorage.setItem('woo-session', headers.get('woocommerce-session'));
      }
    }

    return response;
  });
});

const client = new ApolloClient({
  link: middleware.concat(afterware.concat(httpLink)),
  cache,
  clientState: {},
});
```

Does this close any currently open issues?
------------------------------------------
…

Any relevant logs, error output, GraphiQL screenshots, etc?
-------------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
…

Where has this been tested?
---------------------------
**Operating System:** Ubuntu 18.04

**WordPress Version:** 5.2

### CODE REVIEW

**Comment by jbloth** [comment]
Hi guys, thank you for the great work! Here comes a noob question, so please be patient with me: I am retrieving and sending the woocommerce-session data almost exactly as it is done in the example above. My problem is that the session is expired after two days and I can not add items to the cart anymore. How do I delete the session from local storage once it is expired? The text above says "When the session is destroyed, like when the user logs out, the session header is pass with the value 'false'." but i can't seem to find this 'false' in the header.

Also, excuse me if this is not the right place to ask a question like that. I am sort of new to github as well.

Here is how my Apollo Client looks like:

`import withApollo from 'next-with-apollo';
import fetch from 'node-fetch';
import { ApolloClient } from 'apollo-client';
import { InMemoryCache } from 'apollo-cache-inmemory';
import { createHttpLink } from 'apollo-link-http';
import { ApolloLink } from 'apollo-link';
import { getDataFromTree } from '@apollo/react-ssr';

// needed for getting the price from different product types in Woocommerce Graphql
import { IntrospectionFragmentMatcher } from 'apollo-cache-inmemory';
import introspectionQueryResultData from '../fragmentTypes.json';
import clientConfig from '../clientConfig';

const fragmentMatcher = new IntrospectionFragmentMatcher({
  introspectionQueryResultData,
});

export const sendSessionTokenLink = new ApolloLink((operation, forward) => {
  /**
   * If session data exist in local storage, set value as session header.
   */
  const session = process.browser ? localStorage.getItem('woo-session') : null;
  if (session) {
    operation.setContext(({ headers = {} }) => ({
      headers: {
        'woocommerce-session': `Session ${session}`,
      },
    }));
  }

  return forward(operation);
});


export const receiveSessionTokenLink = new ApolloLink((operation, forward) => {
  return forward(operation).map((response) => {
    /**
     * Check for session header and update session in local storage accordingly.
     */
    const context = operation.getContext();
    const {
      response: { headers },
    } = context;
    const session = headers.get('woocommerce-session');
    console.log(headers);
    console.log(session);

    if (session) {
      if (localStorage.getItem('woo-session') !== session) {
        localStorage.setItem('woo-session', headers.get('woocommerce-session'));
      }
    } 

    return response;
  });
});

function createClient({ headers, initialState }) {
  return new ApolloClient({
    link: sendSessionTokenLink.concat(
      receiveSessionTokenLink.concat(
        createHttpLink({
          uri: clientConfig.graphqlUrl,
          fetch: fetch,
        })
      )
    ),
    cache: new InMemoryCache({ fragmentMatcher }).restore(initialState || {}),
  });
}

export default withApollo(createClient, { getDataFromTree });`

**Comment by MobyDigg** [comment]
@kidunot89 thanks for this. Is there an example with fetch() anywhere online?

**Comment by kidunot89** [comment]
https://woographql.com/playground

**Comment by MobyDigg** [comment]
image

…sorry, I can't find it @kidunot89

**Comment by kidunot89** [comment]
@MobyDigg My bad, I haven't updated the Docs app since the WPGraphQL v1.0. I'll get it updated ASAP. Here is the [React Component](https://github.com/wp-graphql/wp-graphql-woocommerce/blob/develop/docs/src/components/graphiql/index.js) that implements the playground

**Comment by kidunot89** [comment]
@MobyDigg The server has been updated.

**Comment by muhaimincs** [comment]
@kidunot89 any example implementation using React-Native. I thought it should be the same but I keep getting a new woo-commerce session when query or mutation. How to resolve the keep changing woo-commerce session?

**Comment by leftis** [comment]
@kidunot89 Question: Does the woocommerce-session returns on specific calls? For example addToCart mutation returns it? 
I was working with it but then i altered something and broke it and can't find out what. I now get 

{"errors":[{"debugMessage":"Call to a member function add_to_cart() on null","message":"Internal server error","extensions":{"category":"internal"},"locations":[{"line":2,"column":5}],"path":["addToCart"]}],"data":{"addToCart":null},"extensions":{"debug":[]}}

It looks like the response on add-to-cart mutation doesnt  include the woocommerce-session. Any help on it please?

**Comment by kidunot89** [comment]
@leftis You should get a `woocommerce-session` response header after `addToCart`, `login`, and `registerCustomer`. Also note that you can now get the token using the following query
```graphql
customer {
  sessionToken
}
```

**Comment by leftis** [comment]
> @leftis You should get a `woocommerce-session` response header after `addToCart`, `login`, and `registerCustomer`. Also note that you can now get the session token using the following query
> 
> ```graphql
> customer {
>   sessionToken
> }
> ```

Don't know what I am doing wrong, it was working before upgrading on later versions but now for some reason it keeps returning 

{"errors":[{"debugMessage":"Call to a member function add_to_cart() on null","message":"Internal server error","extensions":{"category":"internal"},"locations":[{"line":2,"column":5}],"path":["addToCart"]}],"data":{"addToCart":null},"extensions":{"debug":[]}}

is it a prerequisite to have the jwt plugin installed for the addToCart mutation to work?

**Comment by micmc422** [comment]
I have the exact same issue as @leftis, i try jwt plugin, cors plugins, but not efficient.

problem solved by deleting plugins via ftp and re-installing them on wordpress server.

hope it can help you.

**Comment by gsdavris** [comment]
@kidunot89 How to implement this server side? when the locale storage in not available? (request from api routes)

**Comment by amityweb** [comment]
Surprised I can't find much info about setting this up... 

woocommerce-session is refreshed every time I send a query, though I include the previous one in the header:
`headers: {'woocommerce-session': `Session ${token}` }`

I assume it should stay the same? I am getting new sessions building up in the DB. Not sure what I am doing wrong.

**Comment by garydubb** [comment]
@amityweb I also have this trouble. Did you figure it out? I think, what is happening, every time a request is sent to graphql it creates a new session instead off handling with single, the above logic provides new session at every request. I tried using middleware to create session and store it in cookie and fetch is during apollo request , it is same thing, it seems something is missing when session data is being sent to woocommerce

**Comment by amityweb** [comment]
I did figure it out and I've been meaning to create an issue about because it's due to limitations in this plugin and I e wasted so much time on it. 

In my case it's because this plugin does not provide a "headers" tab like all other GraphQL clients I use. So I've been posting the headers in the box under the graphql box (can't recall what it's called off the top of m head) but I assume that it dies NOT pass the parameters as actual headers. So my woocommerce-session token was not passed. 

I had to install another GraphQL client to post data with, that does have a headers tab, and that worked. 

Absolutely ridiculous this plugin provides a GraphQL interface but no means of passing "headers".

**Comment by garydubb** [comment]
@amityweb I understand what you mean. I will try to figure it out.

**Comment by amityweb** [comment]
I forgot to say, once I realised it was a limitation in this plugin that caused my issue, and I used a better GraphQL app to do my tests and could see the woocommerce-session was working OK, I then implemented it in my code, and the token is working OK. I use Axios on a Next.js project to post the request and the headers have to be submitted as heads in the GraphQL, not part of the main body request.

**Pull request merged**
